name: OneChain Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and Publish
        env:
          # Key is now read securely from GitHub Secrets (Set in Task 164)
          MOVE_PRIVATE_KEY: ${{ secrets.MOVE_PRIVATE_KEY }}
        run: |
          # --- 1. Install Dependencies ---
          # Install apt dependencies needed for the script
          sudo apt-get update
          sudo apt-get install -y curl bash

          # --- 2. Install Sui CLI ---
          # We pipe the script directly to Bash to avoid the "Failure writing output" error.
          echo "Installing Sui CLI..."
          curl -sS https://packagecloud.io/install/repositories/neondapp/sui-cli/script.deb.sh | sudo bash
          sudo apt-get install -y sui-cli

          # --- 3. Run Deployment ---
          export SUI_RPC_URL='https://rpc-testnet.onelabs.cc:443'
          echo "\$MOVE_PRIVATE_KEY" > sui_key.txt
          sui keytool import-private-key --key-file sui_key.txt --env testnet

          echo "Starting final publish transaction on OneChain Testnet..."
          sui move publish --gas-budget 20000000 --json
          
